### ISSUE TITLE
Application does not load data

### ISSUE THREAD

**Issue by ConnorChristensen** [zac-garby/iTunes-Graphs#3]
I'm running MacOS 10.13.4 and the program never loads the music into the pie charts.

It appears that the data is loaded in on the for loop in the ViewController, but the code after the for loop never runs (line 66-72 on the ViewController).

The pie graphs are loading in an empty data set, so the program never shows any content.

**Comment by zac-garby** [comment]
I'm running the same version of macOS as you, so that shouldn't be a problem.

By "the code after the for loop never runs", do you mean the for loop doesn't finish or for some reason that code is skipped?

**Comment by zac-garby** [comment]
Update: I found something which could be the problem. In the for-loop, line 55, there's a bit of code which says:

```swift
guard let artist = track.artist?.name else { return }
```

This would return from the function if one of your tracks doesn't have an artist, which could easily happen if you're not getting music from the iTunes store or Apple Music. I think making this `continue` instead of `return` might fix your problem.

**Comment by ConnorChristensen** [comment]
Yes. Changing that return to a continue fixed it. I think it's better that the app skip a song without an artist rather than do a full stop if the artist is undefined.

**Comment by zac-garby** [comment]
Nice :) Do you wanna make a pull request?
